# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Send Push Notification

on:
  push:
    branches: [ Fyodors-new-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: "6dc13390-13a0-4edf-9961-9fc7216ac108"
        MESSAGE: "There is a new commit!"
